### ISSUE TITLE
question

### ISSUE THREAD

**Issue by LJ191021** [MaterialsInformaticsDemo/DAN#1]
history = model.fit([source_x, target_x, ], source_y_train, batch_size=32, epochs=500,
                    validation_data=([source_x, target_x, ], source_y_train), callbacks=[cp_callback])
when i ran the code, the error below happened, how can i solve this problem?
Traceback (most recent call last):
  File "/mnt/sbd1_newdisk/lzq/DASIG/check.py", line 186, in <module>
    train_model(X_training, y_training, x_testing, y_testing)
  File "/mnt/sbd1_newdisk/lzq/DASIG/check.py", line 173, in train_model
    model.fit([source_x, target_x, ], source_y,
ValueError: Data cardinality is ambiguous:
  x sizes: 39600, 36900
  y sizes: 39600

**Comment by Bin-Cao** [comment]
I apologize for the delay reply. This was originally included as an example in our book, but we ultimately decided not to use it. Since I don't have any time to continue maintaining or revising this unused code. I would appreciate it if you could review and update any potential errors in the code. Thanks you
